// Auto-generated static suggestions for agile fields  
// Generated on: 2025-01-15T10:30:00.000Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate-static-analysis.ts

import type { StaticSuggestionData } from '../../../types/static-suggestions.js';

export const AGILE_STATIC_SUGGESTIONS: StaticSuggestionData = {
  entityType: 'agile',
  
  // Agile-specific spelling corrections (boards, sprints, backlogs)
  typoCorrections: {
    // Board field typos
    'bord': 'board',
    'borad': 'board',
    'borard': 'board',
    'baord': 'board',
    'boad': 'board',
    
    // Sprint field typos
    'sprin': 'sprint',
    'sprnt': 'sprint',
    'spirnt': 'sprint',
    'sprit': 'sprint',
    'spint': 'sprint',
    
    // State field typos
    'stat': 'state',
    'sate': 'state',
    'staet': 'state',
    'stae': 'state',
    'status': 'state',
    
    // Name field typos
    'nam': 'name',
    'namee': 'name',
    'nme': 'name',
    'naem': 'name',
    
    // Start date typos
    'startdat': 'startDate',
    'startdte': 'startDate',
    'strtdate': 'startDate',
    'sdate': 'startDate',
    'start': 'startDate',
    
    // End date typos
    'enddat': 'endDate',
    'enddte': 'endDate',
    'endate': 'endDate',
    'edate': 'endDate',
    'end': 'endDate',
    
    // Complete date typos
    'completedat': 'completeDate',
    'completdate': 'completeDate',
    'compdate': 'completeDate',
    'cdate': 'completeDate',
    'completed': 'completeDate',
    
    // Goal typos
    'gol': 'goal',
    'goall': 'goal',
    'gaol': 'goal',
    'objective': 'goal',
    
    // Board type typos
    'typ': 'type',
    'tpe': 'type',
    'boardtype': 'type',
    'btype': 'type',
    
    // Board location typos
    'loc': 'location',
    'locatin': 'location',
    'loaction': 'location',
    'boardloc': 'location',
    
    // Column config typos
    'column': 'columnConfig',
    'columns': 'columnConfig',
    'colconfig': 'columnConfig',
    'columncfg': 'columnConfig',
    
    // Estimation typos
    'estimate': 'estimation',
    'estimaton': 'estimation',
    'estim': 'estimation',
    'boardestim': 'estimation',
    
    // Filter typos
    'filtr': 'filter',
    'filtter': 'filter',
    'fltr': 'filter',
    'boardfilter': 'filter',
    
    // Permission typos
    'perm': 'permissions',
    'permission': 'permissions',
    'perms': 'permissions',
    'boardperms': 'permissions',
    
    // Backlog typos
    'backlog': 'canEdit',
    'edit': 'canEdit',
    'editable': 'canEdit',
    'canedit': 'canEdit',
    
    // Self URL typos
    'selfurl': 'self',
    'url': 'self',
    
    // ID typos
    'boardid': 'id',
    'sprintid': 'id',
    'ide': 'id',
    'idd': 'id'
  },
  
  // Agile field usage statistics (boards and sprints)
  usageStatistics: {
    // Core board fields (always present)
    'id': { frequency: 'high', availability: 1.0 },
    'name': { frequency: 'high', availability: 0.99 },
    'type': { frequency: 'high', availability: 0.95 },
    'self': { frequency: 'medium', availability: 1.0 },
    
    // Board configuration
    'location': { frequency: 'medium', availability: 0.85 },
    'location.projectId': { frequency: 'medium', availability: 0.85 },
    'location.projectKey': { frequency: 'medium', availability: 0.85 },
    'location.projectName': { frequency: 'medium', availability: 0.85 },
    'location.displayName': { frequency: 'medium', availability: 0.85 },
    'location.projectTypeKey': { frequency: 'low', availability: 0.85 },
    'location.avatarURI': { frequency: 'low', availability: 0.85 },
    
    // Board filtering and access
    'filter': { frequency: 'medium', availability: 0.75 },
    'filter.id': { frequency: 'medium', availability: 0.75 },
    'filter.name': { frequency: 'medium', availability: 0.75 },
    'filter.self': { frequency: 'low', availability: 0.75 },
    'filter.query': { frequency: 'low', availability: 0.75 },
    'filter.description': { frequency: 'low', availability: 0.75 },
    'filter.owner': { frequency: 'low', availability: 0.75 },
    'filter.jql': { frequency: 'low', availability: 0.75 },
    'filter.viewUrl': { frequency: 'low', availability: 0.75 },
    'filter.searchUrl': { frequency: 'low', availability: 0.75 },
    'filter.favourite': { frequency: 'low', availability: 0.75 },
    'filter.subscriptions': { frequency: 'low', availability: 0.75 },
    'filter.sharePermissions': { frequency: 'low', availability: 0.75 },
    
    // Board permissions and capabilities
    'canEdit': { frequency: 'medium', availability: 0.90 },
    'canDelete': { frequency: 'low', availability: 0.90 },
    'canCreateIssue': { frequency: 'medium', availability: 0.90 },
    
    // Board configuration details
    'columnConfig': { frequency: 'low', availability: 0.60 },
    'columnConfig.columns': { frequency: 'low', availability: 0.60 },
    'columnConfig.constraintType': { frequency: 'low', availability: 0.60 },
    
    'estimation': { frequency: 'low', availability: 0.55 },
    'estimation.type': { frequency: 'low', availability: 0.55 },
    'estimation.field': { frequency: 'low', availability: 0.55 },
    
    'ranking': { frequency: 'low', availability: 0.50 },
    'ranking.rankCustomFieldId': { frequency: 'low', availability: 0.50 },
    
    // Sprint-specific fields (when querying sprints)
    'state': { frequency: 'high', availability: 0.95 }, // active, closed, future
    'startDate': { frequency: 'high', availability: 0.80 },
    'endDate': { frequency: 'high', availability: 0.80 },
    'completeDate': { frequency: 'medium', availability: 0.40 }, // Only for closed sprints
    'goal': { frequency: 'medium', availability: 0.65 },
    
    // Sprint board relationship
    'originBoardId': { frequency: 'medium', availability: 0.90 },
    
    // Sprint date and time tracking
    'createdDate': { frequency: 'low', availability: 0.85 },
    'activatedDate': { frequency: 'low', availability: 0.70 },
    
    // Advanced sprint properties
    'synced': { frequency: 'low', availability: 0.60 },
    'sequence': { frequency: 'low', availability: 0.85 },
    
    // Board issue counts (if included in response)
    'issues': { frequency: 'low', availability: 0.30 },
    'issuesEstimateSum': { frequency: 'low', availability: 0.25 },
    'puntedIssues': { frequency: 'low', availability: 0.20 },
    'issuesNotCompletedEstimateSum': { frequency: 'low', availability: 0.20 },
    'completedIssues': { frequency: 'low', availability: 0.25 },
    'issuesCompletedEstimateSum': { frequency: 'low', availability: 0.20 }
  },
  
  // Most commonly used agile fields
  contextualSuggestions: [
    // Core board/sprint identification
    'id',
    'name',
    'state',
    'type',
    
    // Sprint timeline
    'startDate',
    'endDate',
    'goal',
    
    // Board project relationship
    'location',
    'location.projectKey',
    'location.projectName',
    'location.projectId',
    
    // Board capabilities
    'canEdit',
    'canCreateIssue',
    
    // Board filtering
    'filter',
    'filter.id',
    'filter.name',
    'filter.query',
    
    // Sprint metadata
    'originBoardId',
    'completeDate',
    'sequence',
    
    // Advanced board configuration
    'columnConfig',
    'estimation',
    'ranking',
    
    // Sprint progress tracking
    'issues',
    'completedIssues',
    'puntedIssues',
    
    // Additional board properties
    'location.displayName',
    'location.projectTypeKey',
    'filter.jql',
    'filter.description',
    'canDelete',
    
    // Sprint advanced properties
    'createdDate',
    'activatedDate',
    'synced',
    'issuesEstimateSum',
    'issuesCompletedEstimateSum',
    'issuesNotCompletedEstimateSum',
    
    // Extended board configuration
    'columnConfig.columns',
    'columnConfig.constraintType',
    'estimation.type',
    'estimation.field',
    'ranking.rankCustomFieldId'
  ],
  
  // Custom field patterns specific to agile boards and sprints
  customFieldPatterns: {
    // Epic tracking in agile boards
    'epic_link': [
      'customfield_10001',
      'customfield_10002',
      'customfield_10014',
      'customfield_10103'
    ],
    
    // Sprint fields (for issues within sprints)
    'sprint_field': [
      'customfield_10001',
      'customfield_10020',
      'customfield_10100',
      'customfield_10200'
    ],
    
    // Story points for estimation
    'story_points': [
      'customfield_10005',
      'customfield_10016',
      'customfield_10104',
      'customfield_10204'
    ],
    
    // Epic name fields
    'epic_name': [
      'customfield_10004',
      'customfield_10011',
      'customfield_10105'
    ],
    
    // Epic status for kanban boards
    'epic_status': [
      'customfield_10005',
      'customfield_10015',
      'customfield_10106'
    ],
    
    // Flagging fields for agile boards
    'flagged': [
      'customfield_10006',
      'customfield_10017',
      'customfield_10107'
    ],
    
    // Rank/priority fields for board ordering
    'rank': [
      'customfield_10007',
      'customfield_10010',
      'customfield_10108'
    ],
    
    // Team fields for scaled agile
    'team': [
      'customfield_10008',
      'customfield_10018',
      'customfield_10109'
    ],
    
    // Release/PI fields for agile release trains
    'release': [
      'customfield_10009',
      'customfield_10019',
      'customfield_10110'
    ],
    
    // Business value fields for prioritization
    'business_value': [
      'customfield_10012',
      'customfield_10022',
      'customfield_10111'
    ],
    
    // Acceptance criteria fields
    'acceptance_criteria': [
      'customfield_10013',
      'customfield_10023',
      'customfield_10112'
    ],
    
    // Definition of done fields
    'definition_of_done': [
      'customfield_10021',
      'customfield_10024',
      'customfield_10113'
    ]
  },
  
  lastAnalyzed: '2025-01-15T10:30:00.000Z'
};