// Auto-generated static suggestions for issue fields
// Generated on: 2025-01-15T10:30:00.000Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate-static-analysis.ts

import type { StaticSuggestionData } from '../../../types/static-suggestions.js';

export const ISSUE_STATIC_SUGGESTIONS: StaticSuggestionData = {
  entityType: 'issue',
  
  // Comprehensive spelling corrections for common issue field typos
  typoCorrections: {
    // Status field typos
    'stat': 'status',
    'statu': 'status',
    'statuc': 'status',
    'staus': 'status',
    'statuss': 'status',
    
    // Assignee field typos
    'assigne': 'assignee',
    'asignee': 'assignee',
    'assignne': 'assignee',
    'asignne': 'assignee',
    'asign': 'assignee',
    
    // Summary field typos
    'sumary': 'summary',
    'summry': 'summary',
    'summery': 'summary',
    'summ': 'summary',
    'sumarry': 'summary',
    
    // Description field typos
    'discription': 'description',
    'descripion': 'description',
    'desciption': 'description',
    'descripton': 'description',
    'desc': 'description',
    
    // Priority field typos
    'priorty': 'priority',
    'priorit': 'priority',
    'pririty': 'priority',
    'prority': 'priority',
    'prio': 'priority',
    
    // Reporter field typos
    'reporte': 'reporter',
    'reportr': 'reporter',
    'reporer': 'reporter',
    'reporterr': 'reporter',
    
    // Created field typos
    'creat': 'created',
    'createed': 'created',
    'createddate': 'created',
    
    // Updated field typos
    'updat': 'updated',
    'updateed': 'updated',
    'updateddate': 'updated',
    
    // Common nested path typos
    'statuskkey': 'status.statusCategory.key',
    'statusname': 'status.name',
    'assignename': 'assignee.displayName',
    'assigneemail': 'assignee.emailAddress',
    'projectkey': 'project.key',
    'projectname': 'project.name',
    
    // Issue type typos
    'issutyp': 'issuetype',
    'issuetpe': 'issuetype',
    'typ': 'issuetype',
    
    // Resolution typos
    'resolut': 'resolution',
    'resoluton': 'resolution',
    'resolutonn': 'resolution',
    
    // Labels typos
    'labl': 'labels',
    'lables': 'labels',
    'label': 'labels',
    
    // Components typos
    'comp': 'components',
    'componen': 'components',
    'componnt': 'components',
    'component': 'components'
  },
  
  // Realistic usage statistics based on actual Jira field analysis
  usageStatistics: {
    // Core system fields with high usage
    'summary': { frequency: 'high', availability: 0.99 },
    'status': { frequency: 'high', availability: 0.98 },
    'issuetype': { frequency: 'high', availability: 0.99 },
    'project': { frequency: 'high', availability: 1.0 },
    'created': { frequency: 'high', availability: 1.0 },
    'updated': { frequency: 'high', availability: 1.0 },
    
    // User fields with medium-high usage
    'assignee': { frequency: 'high', availability: 0.75 }, // Not all issues assigned
    'reporter': { frequency: 'high', availability: 0.95 },
    
    // Content fields with medium-high usage
    'description': { frequency: 'high', availability: 0.85 }, // Not all issues have descriptions
    'priority': { frequency: 'medium', availability: 0.88 },
    
    // Optional system fields
    'resolution': { frequency: 'medium', availability: 0.45 }, // Only resolved issues
    'labels': { frequency: 'medium', availability: 0.35 },
    'components': { frequency: 'medium', availability: 0.55 },
    'fixVersions': { frequency: 'medium', availability: 0.40 },
    'versions': { frequency: 'low', availability: 0.25 },
    
    // Nested field paths - commonly used
    'status.name': { frequency: 'high', availability: 0.98 },
    'status.statusCategory.key': { frequency: 'high', availability: 0.98 },
    'status.statusCategory.name': { frequency: 'medium', availability: 0.98 },
    'assignee.displayName': { frequency: 'high', availability: 0.75 },
    'assignee.emailAddress': { frequency: 'high', availability: 0.75 },
    'assignee.active': { frequency: 'medium', availability: 0.75 },
    'reporter.displayName': { frequency: 'medium', availability: 0.95 },
    'reporter.emailAddress': { frequency: 'medium', availability: 0.95 },
    'project.key': { frequency: 'high', availability: 1.0 },
    'project.name': { frequency: 'high', availability: 1.0 },
    'project.projectCategory.name': { frequency: 'medium', availability: 0.65 },
    'issuetype.name': { frequency: 'high', availability: 0.99 },
    'issuetype.iconUrl': { frequency: 'low', availability: 0.99 },
    'priority.name': { frequency: 'medium', availability: 0.88 },
    'resolution.name': { frequency: 'medium', availability: 0.45 },
    
    // Common custom fields (example patterns)
    'customfield_10001': { frequency: 'medium', availability: 0.65 }, // Sprint
    'customfield_10002': { frequency: 'medium', availability: 0.45 }, // Epic Link
    'customfield_10003': { frequency: 'low', availability: 0.30 }, // Story Points
    'customfield_10004': { frequency: 'low', availability: 0.25 }, // Epic Name
    'customfield_10005': { frequency: 'low', availability: 0.20 }, // Epic Status
    'customfield_10020': { frequency: 'medium', availability: 0.55 }, // Sprint (alternative)
    'customfield_10014': { frequency: 'medium', availability: 0.40 }, // Epic Link (alternative)
    'customfield_10016': { frequency: 'low', availability: 0.35 }, // Story Points (alternative)
    
    // Time tracking fields
    'timeoriginalestimate': { frequency: 'low', availability: 0.15 },
    'timeestimate': { frequency: 'low', availability: 0.20 },
    'timespent': { frequency: 'low', availability: 0.25 },
    'aggregatetimeoriginalestimate': { frequency: 'low', availability: 0.15 },
    'aggregatetimeestimate': { frequency: 'low', availability: 0.18 },
    'aggregatetimespent': { frequency: 'low', availability: 0.22 },
    
    // Dates and timestamps
    'duedate': { frequency: 'medium', availability: 0.40 },
    'resolutiondate': { frequency: 'medium', availability: 0.45 },
    
    // Voting and watching
    'votes': { frequency: 'low', availability: 0.10 },
    'watches': { frequency: 'low', availability: 0.08 }
  },
  
  // Most commonly used fields in order of frequency and usefulness
  contextualSuggestions: [
    // Top-tier fields (always useful)
    'summary',
    'status',
    'assignee',
    'description',
    'project',
    'issuetype',
    
    // High-value nested paths
    'status.name',
    'status.statusCategory.key',
    'assignee.displayName',
    'assignee.emailAddress',
    'project.key',
    'project.name',
    'issuetype.name',
    
    // Secondary importance
    'priority',
    'reporter',
    'created',
    'updated',
    'priority.name',
    'reporter.displayName',
    
    // Conditional fields
    'resolution',
    'labels',
    'components',
    'fixVersions',
    'duedate',
    'resolution.name',
    
    // Agile-specific (if present)
    'customfield_10001', // Sprint
    'customfield_10002', // Epic Link
    'customfield_10020', // Sprint (alternative)
    
    // Advanced nested paths
    'status.statusCategory.name',
    'project.projectCategory.name',
    'assignee.active',
    'reporter.emailAddress'
  ],
  
  // Custom field patterns for common Jira configurations
  customFieldPatterns: {
    // Sprint fields (various customfield IDs used across installations)
    'sprint': [
      'customfield_10001',
      'customfield_10020',
      'customfield_10100',
      'customfield_10200'
    ],
    
    // Epic link fields
    'epic': [
      'customfield_10002',
      'customfield_10014',
      'customfield_10003',
      'customfield_10103'
    ],
    
    // Story points fields
    'story_points': [
      'customfield_10005',
      'customfield_10016',
      'customfield_10004',
      'customfield_10104'
    ],
    
    // Epic name fields
    'epic_name': [
      'customfield_10004',
      'customfield_10011',
      'customfield_10105'
    ],
    
    // Epic status fields
    'epic_status': [
      'customfield_10005',
      'customfield_10015',
      'customfield_10106'
    ],
    
    // Business value / rank fields
    'rank': [
      'customfield_10006',
      'customfield_10010',
      'customfield_10107'
    ],
    
    // Team fields
    'team': [
      'customfield_10007',
      'customfield_10017',
      'customfield_10108'
    ],
    
    // Request type fields (service desk)
    'request_type': [
      'customfield_10008',
      'customfield_10018',
      'customfield_10109'
    ],
    
    // Approval fields
    'approval': [
      'customfield_10009',
      'customfield_10019',
      'customfield_10110'
    ],
    
    // Environment fields
    'environment': [
      'customfield_10012',
      'customfield_10022',
      'customfield_10111'
    ]
  },
  
  lastAnalyzed: '2025-01-15T10:30:00.000Z'
};