// Auto-generated static suggestions for project fields
// Generated on: 2025-01-15T10:30:00.000Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate-static-analysis.ts

import type { StaticSuggestionData } from '../../../types/static-suggestions.js';

export const PROJECT_STATIC_SUGGESTIONS: StaticSuggestionData = {
  entityType: 'project',
  
  // Project-specific spelling corrections
  typoCorrections: {
    // Project field typos
    'projct': 'project',
    'projet': 'project',
    'proect': 'project',
    'projetc': 'project',
    
    // Key field typos
    'keey': 'key',
    'ky': 'key',
    'keyy': 'key',
    'ke': 'key',
    
    // Name field typos
    'nam': 'name',
    'namee': 'name',
    'nme': 'name',
    'naem': 'name',
    
    // Description typos
    'desc': 'description',
    'discription': 'description',
    'descripion': 'description',
    'desciption': 'description',
    
    // Lead typos
    'leed': 'lead',
    'leadd': 'lead',
    'projlead': 'lead',
    'projectlead': 'lead',
    
    // Category typos
    'categor': 'projectCategory',
    'category': 'projectCategory',
    'cat': 'projectCategory',
    'projectcat': 'projectCategory',
    'projcat': 'projectCategory',
    
    // URL typos
    'ur': 'url',
    'urll': 'url',
    'projurl': 'url',
    'projecturl': 'url',
    
    // Avatar typos
    'avatr': 'avatarUrls',
    'avatar': 'avatarUrls',
    'avtar': 'avatarUrls',
    'avatarurl': 'avatarUrls',
    
    // Issue types typos
    'issutyp': 'issueTypes',
    'issuetypes': 'issueTypes',
    'issuetpe': 'issueTypes',
    'issuetyps': 'issueTypes',
    
    // Versions typos
    'version': 'versions',
    'versio': 'versions',
    'vers': 'versions',
    'versns': 'versions',
    
    // Components typos
    'comp': 'components',
    'componen': 'components',
    'componnt': 'components',
    'component': 'components',
    'comps': 'components',
    
    // Roles typos
    'rol': 'roles',
    'roless': 'roles',
    'role': 'roles',
    'projroles': 'roles',
    
    // Properties typos
    'prop': 'properties',
    'propertie': 'properties',
    'props': 'properties',
    'propertys': 'properties'
  },
  
  // Project field usage statistics
  usageStatistics: {
    // Core project fields (always present)
    'key': { frequency: 'high', availability: 1.0 },
    'name': { frequency: 'high', availability: 1.0 },
    'id': { frequency: 'high', availability: 1.0 },
    'self': { frequency: 'medium', availability: 1.0 },
    
    // Leadership and ownership
    'lead': { frequency: 'high', availability: 0.95 },
    'lead.displayName': { frequency: 'high', availability: 0.95 },
    'lead.emailAddress': { frequency: 'medium', availability: 0.95 },
    'lead.active': { frequency: 'medium', availability: 0.95 },
    
    // Project metadata
    'description': { frequency: 'medium', availability: 0.75 },
    'url': { frequency: 'low', availability: 0.35 },
    'email': { frequency: 'low', availability: 0.25 },
    
    // Categorization
    'projectCategory': { frequency: 'medium', availability: 0.65 },
    'projectCategory.name': { frequency: 'medium', availability: 0.65 },
    'projectCategory.description': { frequency: 'low', availability: 0.65 },
    'projectCategory.id': { frequency: 'low', availability: 0.65 },
    
    // Visual elements
    'avatarUrls': { frequency: 'medium', availability: 0.90 },
    'avatarUrls.16x16': { frequency: 'low', availability: 0.90 },
    'avatarUrls.24x24': { frequency: 'low', availability: 0.90 },
    'avatarUrls.32x32': { frequency: 'low', availability: 0.90 },
    'avatarUrls.48x48': { frequency: 'medium', availability: 0.90 },
    
    // Project configuration
    'projectTypeKey': { frequency: 'medium', availability: 0.85 },
    'simplified': { frequency: 'low', availability: 0.80 },
    'style': { frequency: 'low', availability: 0.75 },
    'isPrivate': { frequency: 'medium', availability: 0.70 },
    
    // Project structure elements
    'issueTypes': { frequency: 'high', availability: 0.95 },
    'versions': { frequency: 'medium', availability: 0.60 },
    'components': { frequency: 'medium', availability: 0.55 },
    'roles': { frequency: 'low', availability: 0.40 },
    
    // Extended properties
    'properties': { frequency: 'low', availability: 0.30 },
    'insight': { frequency: 'low', availability: 0.25 },
    'deleted': { frequency: 'low', availability: 0.10 },
    'retentionTillDate': { frequency: 'low', availability: 0.05 },
    'deletedDate': { frequency: 'low', availability: 0.05 },
    'deletedBy': { frequency: 'low', availability: 0.05 },
    
    // Nested issue type properties
    'issueTypes[].name': { frequency: 'high', availability: 0.95 },
    'issueTypes[].description': { frequency: 'medium', availability: 0.95 },
    'issueTypes[].iconUrl': { frequency: 'low', availability: 0.95 },
    'issueTypes[].subtask': { frequency: 'medium', availability: 0.95 },
    
    // Nested version properties
    'versions[].name': { frequency: 'medium', availability: 0.60 },
    'versions[].description': { frequency: 'low', availability: 0.60 },
    'versions[].released': { frequency: 'medium', availability: 0.60 },
    'versions[].archived': { frequency: 'medium', availability: 0.60 },
    'versions[].releaseDate': { frequency: 'low', availability: 0.60 },
    
    // Nested component properties
    'components[].name': { frequency: 'medium', availability: 0.55 },
    'components[].description': { frequency: 'low', availability: 0.55 },
    'components[].lead': { frequency: 'low', availability: 0.55 },
    'components[].assigneeType': { frequency: 'low', availability: 0.55 },
    'components[].realAssigneeType': { frequency: 'low', availability: 0.55 }
  },
  
  // Most commonly used project fields
  contextualSuggestions: [
    // Essential project identifiers
    'key',
    'name',
    'id',
    
    // Project leadership
    'lead',
    'lead.displayName',
    'lead.emailAddress',
    
    // Project metadata
    'description',
    'projectCategory',
    'projectCategory.name',
    
    // Visual and UI elements
    'avatarUrls',
    'avatarUrls.48x48',
    
    // Project configuration
    'projectTypeKey',
    'isPrivate',
    'style',
    
    // Project structure
    'issueTypes',
    'versions',
    'components',
    
    // Advanced project properties
    'url',
    'email',
    'simplified',
    'properties',
    
    // Nested structure access
    'issueTypes[].name',
    'versions[].name',
    'components[].name',
    'projectCategory.description',
    'lead.active',
    
    // Extended metadata
    'issueTypes[].subtask',
    'versions[].released',
    'components[].lead',
    'roles'
  ],
  
  // Custom field patterns for projects (typically fewer than issues)
  customFieldPatterns: {
    // Business alignment fields
    'business_unit': [
      'customfield_11001',
      'customfield_11010',
      'customfield_11020'
    ],
    
    // Project management fields
    'project_manager': [
      'customfield_11002',
      'customfield_11011',
      'customfield_11021'
    ],
    
    // Budget and finance fields
    'budget': [
      'customfield_11003',
      'customfield_11012',
      'customfield_11022'
    ],
    
    // Timeline fields
    'start_date': [
      'customfield_11004',
      'customfield_11013',
      'customfield_11023'
    ],
    
    'end_date': [
      'customfield_11005',
      'customfield_11014',
      'customfield_11024'
    ],
    
    // Priority and classification
    'business_priority': [
      'customfield_11006',
      'customfield_11015',
      'customfield_11025'
    ],
    
    // Compliance and governance
    'compliance_level': [
      'customfield_11007',
      'customfield_11016',
      'customfield_11026'
    ],
    
    // Integration fields
    'external_id': [
      'customfield_11008',
      'customfield_11017',
      'customfield_11027'
    ],
    
    // Portfolio management
    'portfolio': [
      'customfield_11009',
      'customfield_11018',
      'customfield_11028'
    ]
  },
  
  lastAnalyzed: '2025-01-15T10:30:00.000Z'
};