// Auto-generated static suggestions for user fields
// Generated on: 2025-01-15T10:30:00.000Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate-static-analysis.ts

import type { StaticSuggestionData } from '../../../types/static-suggestions.js';

export const USER_STATIC_SUGGESTIONS: StaticSuggestionData = {
  entityType: 'user',
  
  // User-specific spelling corrections
  typoCorrections: {
    // Display name typos
    'displaynam': 'displayName',
    'displaynme': 'displayName',
    'displyname': 'displayName',
    'dispname': 'displayName',
    'dname': 'displayName',
    'name': 'displayName',
    
    // Email address typos
    'emailaddres': 'emailAddress',
    'emailadress': 'emailAddress',
    'emailadr': 'emailAddress',
    'emal': 'emailAddress',
    'email': 'emailAddress',
    'mail': 'emailAddress',
    'emial': 'emailAddress',
    
    // Active status typos
    'activ': 'active',
    'actve': 'active',
    'activee': 'active',
    'atcive': 'active',
    'enabled': 'active',
    'status': 'active',
    
    // Account ID typos
    'accounti': 'accountId',
    'accid': 'accountId',
    'userid': 'accountId',
    'useraccountid': 'accountId',
    'accountkey': 'accountId',
    'acckey': 'accountId',
    
    // Account type typos
    'accounttyp': 'accountType',
    'acctype': 'accountType',
    'usertype': 'accountType',
    'usrtype': 'accountType',
    
    // Avatar URLs typos
    'avatr': 'avatarUrls',
    'avatar': 'avatarUrls',
    'avtar': 'avatarUrls',
    'avatarurl': 'avatarUrls',
    'avatarurls': 'avatarUrls',
    
    // Self URL typos
    'selfurl': 'self',
    'url': 'self',
    
    // Timezone typos
    'timzon': 'timeZone',
    'timezone': 'timeZone',
    'tz': 'timeZone',
    'zone': 'timeZone',
    
    // Locale typos
    'local': 'locale',
    'locle': 'locale',
    'localee': 'locale',
    'lang': 'locale',
    'language': 'locale',
    
    // Groups typos
    'group': 'groups',
    'grps': 'groups',
    'grp': 'groups',
    'usergroups': 'groups',
    'grups': 'groups',
    
    // Application roles typos
    'roles': 'applicationRoles',
    'approles': 'applicationRoles',
    'applicationrole': 'applicationRoles',
    
    // Expand typos
    'expnd': 'expand',
    'expandd': 'expand',
    'expan': 'expand'
  },
  
  // User field usage statistics
  usageStatistics: {
    // Core user identity fields (always present)
    'accountId': { frequency: 'high', availability: 1.0 },
    'displayName': { frequency: 'high', availability: 0.99 },
    'active': { frequency: 'high', availability: 1.0 },
    'self': { frequency: 'medium', availability: 1.0 },
    
    // Contact information
    'emailAddress': { frequency: 'high', availability: 0.95 },
    
    // Visual elements
    'avatarUrls': { frequency: 'medium', availability: 0.85 },
    'avatarUrls.16x16': { frequency: 'low', availability: 0.85 },
    'avatarUrls.24x24': { frequency: 'low', availability: 0.85 },
    'avatarUrls.32x32': { frequency: 'low', availability: 0.85 },
    'avatarUrls.48x48': { frequency: 'medium', availability: 0.85 },
    
    // User preferences and settings
    'timeZone': { frequency: 'low', availability: 0.70 },
    'locale': { frequency: 'low', availability: 0.65 },
    
    // Account classification
    'accountType': { frequency: 'medium', availability: 0.80 },
    
    // Extended user information (when expanded)
    'groups': { frequency: 'low', availability: 0.40 },
    'applicationRoles': { frequency: 'low', availability: 0.35 },
    'expand': { frequency: 'low', availability: 0.30 },
    
    // Legacy fields (may be present in older Jira versions)
    'name': { frequency: 'low', availability: 0.20 }, // Legacy username field
    'key': { frequency: 'low', availability: 0.15 }, // Legacy user key
    
    // Nested group properties (when groups expanded)
    'groups[].name': { frequency: 'low', availability: 0.40 },
    'groups[].self': { frequency: 'low', availability: 0.40 },
    
    // Nested application role properties (when roles expanded)
    'applicationRoles[].key': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].name': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].defaultGroups': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].selectedByDefault': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].defined': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].numberOfSeats': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].remainingSeats': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].userCount': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].userCountDescription': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].hasUnlimitedSeats': { frequency: 'low', availability: 0.35 },
    'applicationRoles[].platform': { frequency: 'low', availability: 0.35 }
  },
  
  // Most commonly used user fields
  contextualSuggestions: [
    // Essential user identification
    'accountId',
    'displayName',
    'emailAddress',
    'active',
    
    // Common visual and metadata
    'avatarUrls',
    'avatarUrls.48x48',
    'self',
    
    // User classification
    'accountType',
    
    // User preferences
    'timeZone',
    'locale',
    
    // Extended information (less common)
    'groups',
    'applicationRoles',
    
    // Nested access patterns
    'groups[].name',
    'applicationRoles[].key',
    'applicationRoles[].name',
    
    // Legacy fields (for compatibility)
    'name',
    'key',
    
    // Other avatar sizes
    'avatarUrls.16x16',
    'avatarUrls.24x24',
    'avatarUrls.32x32',
    
    // Advanced role information
    'applicationRoles[].defaultGroups',
    'applicationRoles[].userCount',
    'applicationRoles[].hasUnlimitedSeats'
  ],
  
  // Custom field patterns for users (typically very few)
  customFieldPatterns: {
    // Employee information fields
    'employee_id': [
      'customfield_12001',
      'customfield_12010',
      'customfield_12020'
    ],
    
    // Department fields
    'department': [
      'customfield_12002',
      'customfield_12011',
      'customfield_12021'
    ],
    
    // Manager fields
    'manager': [
      'customfield_12003',
      'customfield_12012',
      'customfield_12022'
    ],
    
    // Location fields
    'location': [
      'customfield_12004',
      'customfield_12013',
      'customfield_12023'
    ],
    
    // Phone number fields
    'phone': [
      'customfield_12005',
      'customfield_12014',
      'customfield_12024'
    ],
    
    // Cost center fields
    'cost_center': [
      'customfield_12006',
      'customfield_12015',
      'customfield_12025'
    ],
    
    // Skill set fields
    'skills': [
      'customfield_12007',
      'customfield_12016',
      'customfield_12026'
    ],
    
    // Start date fields
    'start_date': [
      'customfield_12008',
      'customfield_12017',
      'customfield_12027'
    ]
  },
  
  lastAnalyzed: '2025-01-15T10:30:00.000Z'
};